version: '3.9'
x-spring-api-variables: &api-variables
  SERVER_HOST: http://localhost:8080

  AUTH_URL: /auth
  LOGIN_ENDPOINT: /login
  SIGNUP_ENDPOINT: /signup
  LOGOUT_ENDPOINT: /logout

  USER_URL: /user
  ALL_USERS_ENDPOINT: /all

  EVENT_URL: /event
  ALL_EVENTS_ENDPOINTS: /all
  ADD_EVENT_ENDPOINT: /add
  REMOVE_EVENT_ENDPOINT: /remove
services:
  api:
    container_name: rso-app-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    environment: *api-variables
